title = "Nebez Briefkani"
baseURL = "https://nebezb.com"
languageCode = "en-us"
enableRobotsTXT = true
disableKinds = ["section", "RSS", "taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-48047334-1"
publishDir = "docs"

# This is used for the OpenGraph/SEO meta headers.
[params]
  title = "Nebez Briefkani"
  description = "Software engineer, startup enthusiast, and consultant located in Montréal. Currently Principal Engineer, Payments at Lightspeed. Previously SSENSE, LXRandCo, Nukern."
  tags = ["nebez","nebezb","briefkani","web","designer","developer","software","dev","consultant","montreal","quebec","canada","ssense","lxrco","lxrandco","nukern","lightspeed","engineer","latitude85"]

[permalinks]
  posts = "/:slug/"

[frontmatter]
  date = [":filename", ":default"]


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4
